### PR TITLE
update jenkins version.

### PR DESCRIPTION
**Pull request by haraprasadj**
update jenkins version to 2.298

### CODE REVIEW

**Review by themarcelor — APPROVED** [review]
+1

**Comment by themarcelor** [comment]
FYI: The build failed in Quay:
```
/bin/sh: 1: lsb_release: not found
```

**Comment by haraprasadj** [comment]
> FYI: The build failed in Quay:
> 
> ```
> /bin/sh: 1: lsb_release: not found
> ```

The python installation steps are corrupting lsb_release, so moved steps requiring it above

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
