### PR TITLE
Address external PR's

### PR DESCRIPTION
**Pull request by jawadqur**
A couple of external PR's related to generalizing our terraform and availability zones.

### CODE REVIEW

**Comment by jawadqur** [comment]
I am seeing some errors on the integration tests for this, will take a look into them.

**Comment by reisingerf** [comment]
There may be a small syntax error (not sure if I missed that in my PR or if that's due to TerraForm version changes), that we fixed in our fork: https://github.com/umccr/cloud-automation/commit/b73a467f62e2e2a35a3ea4190a27cb0c88f060ef

Not sure that's the issue you are having...

**Comment by jawadqur** [comment]
> There may be a small syntax error (not sure if I missed that in my PR or if that's due to TerraForm version changes), that we fixed in our fork: [umccr@b73a467](https://github.com/umccr/cloud-automation/commit/b73a467f62e2e2a35a3ea4190a27cb0c88f060ef)
> 
> Not sure that's the issue you are having...

That was indeed one of the issues, I was able to resolve the unit test locally with this

**Comment by jawadqur** [comment]
Had to add the default AZ's back to variables since having more than 3 AZ's break our subnetting setup. 

```
[1m[31mError: [0m[0m[1mError running plan: 1 error occurred:
	* module.eks.aws_subnet.eks_private: 3 errors occurred:
	* module.eks.aws_subnet.eks_private[3]: cidrsubnet: prefix extension of 2 does not accommodate a subnet numbered 4 in:

$****var.workers_subnet_size == 22 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 2 , ( 1 + count.index )) : var.workers_subnet_size == 23 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 3 , ( 2 + count.index )) : cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 4 , ( 7 + count.index )) }
	* module.eks.aws_subnet.eks_private[5]: cidrsubnet: prefix extension of 2 does not accommodate a subnet numbered 6 in:

$****var.workers_subnet_size == 22 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 2 , ( 1 + count.index )) : var.workers_subnet_size == 23 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 3 , ( 2 + count.index )) : cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 4 , ( 7 + count.index )) }
	* module.eks.aws_subnet.eks_private[4]: cidrsubnet: prefix extension of 2 does not accommodate a subnet numbered 5 in:

$****var.workers_subnet_size == 22 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 2 , ( 1 + count.index )) : var.workers_subnet_size == 23 ? cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 3 , ( 2 + count.index )) : cidrsubnet(data.aws_vpc.the_vpc.cidr_block, 4 , ( 7 + count.index )) }



[0m

[0m[0m[0m
[31mnon zero exit code from terraform plan: 1[39m

[31mtest_eks_workspace - Assertion failed:[39m tfplan eks should run ok

```

**Comment by reisingerf** [comment]
So, the issue here is that the subnet calculation/setup does not support more than 3 AZs?

Could this not be updated to allow any (reasonable) number of subnets?

If that's not possible/too complex, would the introduction of a `max_supported_subnets` value help?

The list of available AZs (generated in the locals section) could be sliced to the max length if needed?
This would avoid the hard coding of the AZs. If not, this should be highlighted in the documentation, as it's not apparent from the current docs. Perhaps a short section on deployment outside the default `us-east-1` region.

**Comment by jawadqur** [comment]
I don't think we need `max_supported_subnets`. We still retain the functionality of calculating subnets, you can enforece that by supplying an empty list for the availability_zones variable in config.tfvars when before you run `gen3 tfplan`. 

```
availability_zones=[]
```

I believe this is the best approach since: 
- This will ensure that all existing commons will not experience any downtime due to this change
- we can support other regions and AZ's 
- Calculate AZ's by supplying empty list. 

I am satisfied with my testing and I also see Jenkins tests have passed now. 

I am ready to merge your changes if you are satisfied with this explanation.

**Comment by reisingerf** [comment]
OK, fair enough!
Thanks for pushing this through!

**Comment by victorskl** [comment]
Thanks @jawadqur for review. This looks all good from our side. Appreciate it!

**Review by emalinowski — APPROVED** [review]

**Pull request merged**
