### PR TITLE
Update workon.sh

### PR DESCRIPTION
**Pull request by grugna**
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### CODE REVIEW

**Review by emalinowski — APPROVED** [review]

**Comment by grugna** [comment]
@jawadqur let me know if there is anything else to do on my side here.

**Comment by grugna** [comment]
@emalinowski could you trigger the test to merge this in?

**Comment by grugna** [comment]
@emalinowski Could you merge this?

**Review by emalinowski — APPROVED** [review]

**Comment by jawadqur** [comment]
Tested and it doesn't break any existing functionality, and it also works around the constraint that us-east-1 is not in the constraint in the aws cli:

https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html

```json
{
  "LocationConstraint": "af-south-1"|"ap-east-1"|"ap-northeast-1"|"ap-northeast-2"|"ap-northeast-3"|"ap-south-1"|"ap-south-2"|"ap-southeast-1"|"ap-southeast-2"|"ap-southeast-3"|"ca-central-1"|"cn-north-1"|"cn-northwest-1"|"EU"|"eu-central-1"|"eu-north-1"|"eu-south-1"|"eu-south-2"|"eu-west-1"|"eu-west-2"|"eu-west-3"|"me-south-1"|"sa-east-1"|"us-east-2"|"us-gov-east-1"|"us-gov-west-1"|"us-west-1"|"us-west-2",
  "Location": {
    "Type": "AvailabilityZone",
    "Name": "string"
  },
  "Bucket": {
    "DataRedundancy": "SingleAvailabilityZone",
    "Type": "Directory"
  }
}

```

image

**Pull request merged**
